force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>My Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunitiy Products</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Prod_Prod_Code__c.field-meta.xml
<CustomField>
    <fullName>Prod_Prod_Code__c</fullName>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Communication Devices</fullName>
                <label>Cable Ties</label>
            </value>
            <value>
                <fullName>Colourless to yellowish clear liquid.</fullName>
                <label>Wire Harness</label>
            </value>
            <value>
                <fullName>Tie Mounts</fullName>
            </value>
            <value>
                <fullName>Polymide</fullName>
            </value>
            <value>
                <fullName>Wire Managment</fullName>
            </value>
            <value>
                <fullName>circut Bord Accessories</fullName>
            </value>
            <value>
                <fullName>Security Seals</fullName>
            </value>
            <value>
                <fullName>Cable Protection</fullName>
            </value>
            <value>
                <fullName>Cord Organix</fullName>
            </value>
            <value>
                <fullName>Flexiform Continous Grommet Strip</fullName>
            </value>
            <value>
                <fullName>Connector Backshells</fullName>
            </value>
            <value>
                <fullName>Electrical Equipment.</fullName>
                <isActive>false</isActive>
                <label>Electrical Equipment.</label>
            </value>
            <value>
                <fullName>Electrical Fixture</fullName>
                <isActive>false</isActive>
                <label>Electrical Fixture</label>
            </value>
            <value>
                <fullName>Fire Alarm Devices</fullName>
                <isActive>false</isActive>
                <label>Fire Alarm Devices</label>
            </value>
            <value>
                <fullName>Lighting Devices</fullName>
                <isActive>false</isActive>
                <label>Lighting Devices</label>
            </value>
            <value>
                <fullName>Lighting Fixture</fullName>
                <isActive>false</isActive>
                <label>Lighting Fixture</label>
            </value>
            <value>
                <fullName>Nurse Call Devices</fullName>
                <isActive>false</isActive>
                <label>Nurse Call Devices</label>
            </value>
            <value>
                <fullName>Telephone Devices</fullName>
                <isActive>false</isActive>
                <label>Telephone Devices</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Product_IS_Active__c.field-meta.xml
<CustomField>
    <fullName>Product_IS_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/demo1.cls
public class demo1 {
    @AuraEnabled
    public Static String getQuoteItem(String  recId){
           
         Quote__c qt=[select id,name from Quote__c where Id=:recId];
         return JSON.serialize(qt);
    }

    @AuraEnabled
    public Static String getOrderItem(String  recId){
           
         Order__c qt=[select id,name from Order__c where Id=:recId];
         return JSON.serialize(qt);
    }
    
    @AuraEnabled
    public static String saveProduct(String data1){
        Map<String, Object> untypedData = (Map<String, Object>) JSON.deserializeUntyped(data1);
        Opportunity__c prod  = new Opportunity__c();
        prod.Name=(String)untypedData.get('PName');
        prod.Prod_Prod_Code__c=(String)untypedData.get('ProductCode');
        prod.Product_Description__c=(String)untypedData.get('productdes');
        prod.Product_Family__c=(String)untypedData.get('ProductType');
        prod.Product_IS_Active__c=(Boolean)untypedData.get('isActive');
        prod.Unit_Price__c=(double)untypedData.get('unitPrice');
        prod.RecordTypeId='0121m000000DscMAAS';
        insert prod;
        return prod.Name;
    }
}