force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>My Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/orderSucessMailHandler.cls
public class orderSucessMailHandler {
 public static void handleInsert(list<Order__c> orderList){
        set<id> orderIdSet  = new set<Id>();
        for(Order__c ord:orderList){
            if(ord.Id!=null){
                orderIdSet.add(ord.Id);
            }
        }
     system.debug(orderIdSet);
        Set<String> emailSet = new Set<String>();
        List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();
        
        for(Order__c orderObj : [select Id,ContractId__c,Name,OrderNumber__c,PrimaryQuote__r.Opportunity__r.Primary_contact__r.Email  from Order__c   WHERE Id IN :orderIdSet AND ContractId__r.CustomerSigned.Email != null]){
            emailSet.add(orderObj.PrimaryQuote__r.Opportunity__r.Primary_contact__r.Email);
            Messaging.SingleEmailMessage emailMessage = new Messaging.SingleEmailMessage();
            emailMessage.setToAddresses(new String[] {orderObj.PrimaryQuote__r.Opportunity__r.Primary_contact__r.Email});
            emailMessage.setSubject('Order Placed Successfully - ' + orderObj.OrderNumber__c);
            String emailBody = '<p>Thank you for placing Order..!!</p>' +
                               '<p>Your order number is: <strong>' + orderObj.OrderNumber__c + '</strong></p>'+
                               '<p>Best regards,<br/>Mentha And Allied</p>';
            emailMessage.setHtmlBody(emailBody);
            emailMessages.add(emailMessage);
        }
        
        Messaging.sendEmail(emailMessages);
        system.debug('emaiil ids that have to send email'+emailSet);

    }
    
}