force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>My Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunitiy Products</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Primary_contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account_Name__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Invoice_Generated__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

force-app/main/default/classes/SendMail.cls
public class SendMail {
    @AuraEnabled(cacheable=true)
    public static String sendEmailWithPDF(String recordId) {
        Quote__c quoteRecord = [SELECT Id, Name,Opportunity__r.Primary_contact__r.Email,Opportunity__r.Name FROM Quote__c WHERE Id = :recordId LIMIT 1];
        //System.debug('quoteRecord'+quoteRecord);
        try {
            // Generate PDF using Visualforce page
            PageReference pageRef = Page.customQuotePDF;
            pageRef.getParameters().put('id', recordId);
            Blob pdfBlob = pageRef.getContentAsPDF();
            System.debug('pdfBlob'+pdfBlob);
            
            // Create an email message
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setSubject('Your Quote Details');
            String emailBody = '<p>Please find the attached quote PDF.</p>' +
                '<p>Best regards,<br/>NOVOFLEX</p>';
            email.setHtmlBody(emailBody);
            
            // Attach the PDF blob to the email
            Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
            attachment.setFileName(quoteRecord.Opportunity__r.Name+'-Quote.pdf');
            attachment.setBody(pdfBlob);
            email.setFileAttachments(new Messaging.EmailFileAttachment[]{attachment});
            
            // Set recipient email address
            email.setToAddresses(new List<String>{quoteRecord.Opportunity__r.Primary_contact__r.Email});// Add recipient email address
            
            
            Messaging.sendEmail(new Messaging.SingleEmailMessage[]{email});
            
            return 'Email sent successfully';
        } catch (Exception e) {
            // Handle exceptions here
            return 'Error sending email: ' + e.getMessage();
        }
    }
    
    @AuraEnabled
    public static String sendInvoicesWithPdf(String recordId) {
        System.debug('recordId => ' + recordId);
        try {
            // Generate PDF using Visualforce page
            PageReference pageRef = Page.customInvoicePDF;
            pageRef.getParameters().put('id', recordId);
            Blob pdfBlob = pageRef.getContentAsPDF();
            
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            
            order__c orderRecord = [SELECT Id,Name, OrderNumber__c, PrimaryQuote__r.Opportunity__r.Primary_contact__r.Email FROM Order__c WHERE Id =: recordId];
            
            String recipientEmail = orderRecord.PrimaryQuote__r.Opportunity__r.Primary_contact__r.Email;
            system.debug('recipientEmail'+recipientEmail);
            if (recipientEmail != null) {
                email.setToAddresses(new List<String>{recipientEmail});
                email.setSubject('Your Order Invoice');
                String emailBody = '<p>Please find the attached Order Invoice PDF.</p>' +
                    '<p>Best regards,<br/>NOVOFLEX</p>';
                email.setHtmlBody(emailBody);
                
                Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
                attachment.setFileName('Invoices.pdf');
                attachment.setBody(pdfBlob);
                email.setFileAttachments(new Messaging.EmailFileAttachment[]{attachment});
                
                Messaging.sendEmail(new Messaging.SingleEmailMessage[]{email});
                //updating order
                    Order__c  ord= new Order__c();
                    ord.Id=recordId;
                    ord.Invoice_Generated__c=true;
                    system.debug('order detail'+ord);
                    if(ord!=null){
                        update ord;
                    } 
                
                return 'Email sent successfully';
              
                    
                
            } else {
                system.debug('Email id is null');	
            }
            return 'Error';
        } catch (Exception e) {
            return 'Error sending email: ' + e.getMessage();
        }
        
        
    }
    
    
}