force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>My Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Line_Description__c.field-meta.xml
<CustomField>
    <fullName>Line_Description__c</fullName>
    <label>Line Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunitiy Products</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunities (Product)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <formula>Quantity__c * Sales_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sub Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>(Sales_Price__c*Quantity__c)-((Discount__c*(Sales_Price__c*Quantity__c))*100/100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/LineItemDescription__c.field-meta.xml
<CustomField>
    <fullName>LineItemDescription__c</fullName>
    <label>Line Item Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Quotes (Product)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Quote__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Quote</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteLineDiscount__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineDiscount__c</fullName>
    <label>Quote Line Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Subtotal__c-( Subtotal__c *Discount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <formula>(Quantity__c * UnitPrice__c)-((Quantity__c * UnitPrice__c)* QuoteLineDiscount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price Quote</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/quoteSyncToOpportunity.cls
public class quoteSyncToOpportunity {
    @AuraEnabled
    public static String syncOpportunity(String quoteId) {
        System.debug('quoteId==> ' + quoteId);
        
        Quote__c quoteRecord = [SELECT Id, Name,Opportunity__c FROM Quote__c WHERE Id = :quoteId LIMIT 1];
        
        System.debug('quoteRecord==> ' + quoteRecord);
        
        list<Quote__c> QuoteLineItem = [select id,Name,QuoteId__c,ListPrice__c, UnitPrice__c,
                                        Quantity__c, QuoteLineDiscount__c,Total_Price__c, 
                                        LineItemDescription__c, Product__c,Product__r.Name,
                                        TotalPrice__c  from Quote__c WHERE QuoteId__c !=null and QuoteId__c =:quoteRecord.Id];
                
        System.debug('QuoteLineItem15==> ' + QuoteLineItem);
        
        List<Opportunity__c> opportunityLineItems = [select Id,List_Price__c,Discount__c, 
                                                     Product__r.Name,Sales_Price__c, Quantity__c, 
                                                     Sub_Total__c,Total_Price__c,Line_Description__c  from Opportunity__c
                                                     Where Opportunity__c !=null and Opportunity__c =:quoteRecord.Opportunity__c ];
        
        System.debug('QuoteLineItem22==> ' + opportunityLineItems);
        if(opportunityLineItems!= null){
            delete opportunityLineItems;
        }
            
            List<Opportunity__c> oppLineItemToInsertList = new List<Opportunity__c>();
                for(Quote__c quoteObj:QuoteLineItem){
                    Opportunity__c oppLineItemToInsert = new Opportunity__c(
                        Name = quoteObj.Product__r.Name,
                        List_Price__c = quoteObj.ListPrice__c,
                        Discount__c = quoteObj.QuoteLineDiscount__c,
                        Product__c = quoteObj.Product__c,
                        Sales_Price__c = quoteObj.UnitPrice__c,
                        Quantity__c = quoteObj.Quantity__c,
                        Line_Description__c = quoteObj.LineItemDescription__c,
                        Opportunity__c = quoteRecord.Opportunity__c,
                        RecordTypeId = '0121m000000DsXpAAK'
                    );
                    oppLineItemToInsertList.add(oppLineItemToInsert);
                }
                System.debug('opportunityLineItems42==> ' + oppLineItemToInsertList);
                if(oppLineItemToInsertList != null){
                    insert oppLineItemToInsertList;
                }
            
        
        
        return 'null';
    }
}