force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>false</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>My Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunitiy Products</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Primary_contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account_Name__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/ServiceDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceDate__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Confirmation</fullName>
                <default>true</default>
                <label>Order Confirmation</label>
            </value>
            <value>
                <fullName>Truck Load Challan</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Dispatch</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
                <isActive>false</isActive>
                <label>Payment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Need Review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

force-app/main/default/classes/SendMailTest.cls
@isTest
public class SendMailTest {

    @isTest
    static void testSendEmailWithPDF() {
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
        Contact testContact = new Contact(LastName = 'Test Contact', Email = 'test@test.com', AccountId = testAccount.Id);
        insert testContact;
        
        Opportunity__c testOpportunity = new Opportunity__c(
            Name = 'Test Opportunity',
            Close_Date__c = Date.today(),
            Account_Name__c = testAccount.Id,
            Primary_contact__c = testContact.Id,
            RecordTypeId='0121m000000DsT8AAK'
        );
        insert testOpportunity;

        Quote__c testQuote = new Quote__c(
            Name = 'Test Quote',
            Status__c = 'Draft',
            Account_Name__c = testAccount.Id,
            Opportunity__c = testOpportunity.Id,
            ExpirationDate__c = Date.today(),
            RecordTypeId='0121m000000Dse8AAC'
        );
        insert testQuote;
		Test.setCurrentPage(Page.customQuotePDF);
        
       
        Test.startTest();
        String result = SendMail.sendEmailWithPDF(testQuote.Id);
        Test.stopTest();

        
    }

   /* @isTest
    static void testSendEmailWithPDF_InvalidInput() {
        Test.startTest();
        String result = SendMail.sendEmailWithPDF(null);
        Test.stopTest();
        
    }*/

    @isTest
    static void testSendInvoicesWithPDF() {
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

        Contact testContact = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'test@example.com', AccountId = testAccount.Id);
        insert testContact;

        Contract testContract = new Contract(
            AccountId = testAccount.Id,
            Status = 'Draft',
            StartDate = Date.today(),
            ContractTerm = 12,
            CustomerSignedId = testContact.Id
        );
        insert testContract;

        Order__c testOrder = new Order__c(
            Name = 'Test Order',
            ContractId__c = testContract.Id,
            EffectiveDate__c = System.today(),
            AccountId__c = testAccount.Id,
            RecordTypeId='0121m000000DsdoAAC',
            ServiceDate__c = system.today()
            
        );
        insert testOrder;

        Test.startTest();
        String result = SendMail.sendInvoicesWithPdf(testOrder.Id);
        Test.stopTest();

       
    }

    @isTest
    static void testSendInvoicesWithPDF_InvalidInput() {
        Test.startTest();
        String result = SendMail.sendInvoicesWithPdf(null);
        Test.stopTest();
        
    }
}