force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>false</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>My Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Line_Description__c.field-meta.xml
<CustomField>
    <fullName>Line_Description__c</fullName>
    <label>Line Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunitiy Products</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunities (Product)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <formula>Quantity__c * Sales_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sub Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <label>Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>(Sales_Price__c*Quantity__c)-((Discount__c*(Sales_Price__c*Quantity__c))*100/100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/LineItemDescription__c.field-meta.xml
<CustomField>
    <fullName>LineItemDescription__c</fullName>
    <label>Line Item Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Quotes (Product)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Quote__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Quote</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteLineDiscount__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineDiscount__c</fullName>
    <label>Quote Line Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Subtotal__c-( Subtotal__c *Discount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <formula>(Quantity__c * UnitPrice__c)-((Quantity__c * UnitPrice__c)* QuoteLineDiscount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price Quote</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

force-app/main/default/objects/Quote__c/recordTypes/Quote_Item.recordType-meta.xml
<RecordType>
    <fullName>Quote_Item</fullName>
    <active>true</active>
    <label>Quote Item</label>
</RecordType>

force-app/main/default/classes/OppToQuoteTriggerHandler.cls
public class OppToQuoteTriggerHandler {
    private static Boolean hasRun = false;
    
    public static Boolean runOnce() {
        if (!hasRun) {
            hasRun = true;
            return false;
        } else {
            return true;
        }
    }
    
    
    public static void handleQuote(List<Quote__c> newList) {
        if (!newList.isEmpty() && newList[0].Opportunity__c != null) {
            handleQuoteInsert(newList);
        } else if (!newList.isEmpty() && newList[0].QuoteId__c != null) {
            handleQuoteUpdate(newList);
        }
    }
    
    public static void handleQuoteInsert(List<Quote__c> newList) {
        if (newList[0].Opportunity__c != null) {
            System.debug('Handling Quote Insert');
            Id recdId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Quote_Item' LIMIT 1].Id;
            List<Quote__c> quoteLineItemsToInsert = new List<Quote__c>();
            Set<Id> oppIds = new Set<Id>();
            List<Id> quoteIds = new List<Id>();
            
            for (Quote__c quote : newList) {
                if (quote.Opportunity__c != null) {
                    oppIds.add(quote.Opportunity__c);
                    quoteIds.add(quote.Id);
                }
            }
            
            List<Opportunity__c> accountList = [SELECT Id, Amount__c, Account_name__c, Account_name__r.BillingAddress,
                                                Account_name__r.ShippingAddress, Account_Name__r.Name FROM Opportunity__c WHERE Id IN :oppIds];
            
            Account acc = [SELECT Id, BillingStreet, BillingCity, BillingState, BillingPostalCode,
                           BillingCountry, ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, ShippingCountry
                           FROM Account WHERE Id = :accountList[0].Account_name__c];
            
            if (!oppIds.isEmpty()) {
                List<Opportunity__c> opportunityLineItems = [SELECT Name, Id, List_Price__c, Discount__c,
                                                             Product__r.Name, Sales_Price__c, Quantity__c, Sub_Total__c, Total_Price__c, Line_Description__c
                                                             FROM Opportunity__c WHERE Opportunity__c != null AND Opportunity__c = :oppIds];
                
                for (Opportunity__c opportunityLineItem : opportunityLineItems) {
                    Quote__c quoteLineItem = new Quote__c(
                        Name = opportunityLineItem.Name,
                        Product__c = opportunityLineItem.Product__c,
                        Quantity__c = opportunityLineItem.Quantity__c,
                        ListPrice__c = opportunityLineItem.List_Price__c,
                        UnitPrice__c = opportunityLineItem.Sales_Price__c,
                        Subtotal__c = opportunityLineItem.Sub_Total__c,
                        QuoteLineDiscount__c = opportunityLineItem.Discount__c,
                        LineItemDescription__c = opportunityLineItem.Line_Description__c,
                        QuoteId__c = quoteIds[0],
                        
                        RecordTypeId = recdId
                    );
                    
                    quoteLineItemsToInsert.add(quoteLineItem);
                }
                
                insert quoteLineItemsToInsert;
                
                Quote__c quoToUpdate = new Quote__c(
                    Id = quoteIds[0],
                    Account_Name__c = accountList[0].Account_Name__c,
                    Subtotal__c = accountList[0].Amount__c,
                    Bill_To_Name__c = accountList[0].Account_name__r.Name,
                    ShippingName__c = accountList[0].Account_name__r.Name,
                    ShippingAddress__City__s = acc.ShippingCity,
                    ShippingAddress__PostalCode__s = acc.ShippingPostalCode,
                    Bill_To__City__s = acc.BillingCity,
                    Bill_To__PostalCode__s = acc.BillingPostalCode,
                    ShippingAddress__Street__s = acc.ShippingStreet,
                    Bill_To__Street__s = acc.BillingStreet,
                    Discount__c=0.0,
                    ShippingHandling__c=0.0
                );
                
                update quoToUpdate;
            }
         } //else{
        //     system.debug('start');
        //     id quoteId=newList[0].QuoteId__c;
        //     double amount=0.00;
        //     list<Quote__c> Quoteamount =[select id,TotalPrice__c,QuoteId__c from Quote__c where QuoteId__c =:quoteId];
        //     system.debug('before update' +amount);
        //     for(Quote__c qu:Quoteamount){
        //         if(qu.TotalPrice__c!=null){
        //             amount+=qu.TotalPrice__c;
        //         }
        //     }
        //     system.debug('after update' +amount);
        //     Quote__c  quoToUpdate=new  Quote__c();
        //     quoToUpdate.Id=quoteId;
        //     quoToUpdate.Subtotal__c=amount;
        //     system.debug('amount jjshjsh'+quoToUpdate);
        //     if(quoToUpdate!=null){
        //         update quoToUpdate;
        //     }
        // }
        
    }
    
    
    public static void handleQuoteUpdate(List<Quote__c> newList) {
        id quoteId=newList[0].QuoteId__c; 
        system.debug('newList'+newList);
        list<Quote__c> quoToUpdateList = new list<Quote__c>();
        if (newList[0].RecordTypeId!='0121m000000DseDAAS') {
            System.debug('Handling Quote Update');
            for(Quote__c qu:newList){
                if(qu.Id!=null){
                    Quote__c quoToUpdate = new Quote__c();
                    quoToUpdate.id=qu.id;
                    quoToUpdate.name = qu.Name;
                    quoToUpdate.Discount__c=qu.Discount__c;
                    quoToUpdate.Subtotal__c = qu.Subtotal__c;
                    quoToUpdate.ExpirationDate__c=qu.ExpirationDate__c;
                    quoToUpdateList.add(quoToUpdate);
                }
            }
            
            if(quoToUpdateList!=null){
                update quoToUpdateList;
            }            
            
         }//else {
        //     id quoteIds=newList[0].QuoteId__c;
        //     list<Quote__c>  quoteamountlist =[select id,TotalPrice__c,QuoteId__c from Quote__c where QuoteId__c =:quoteIds];
        //     double amount =0.0;
        //      for(Quote__c qu:quoteamountlist){
        //         if(qu.TotalPrice__c!=null){
        //             amount+=qu.TotalPrice__c;
        //         }
        //     }
        //     Quote__c  quoToUpdate=new  Quote__c();
        //     quoToUpdate.Id=quoteId;
        //     quoToUpdate.Subtotal__c=amount;
        //     system.debug('amount jjshjsh tri'+quoToUpdate);
        //     if(quoToUpdate!=null){
        //         update quoToUpdate;
        //     }
            
        //     System.debug('QuoteId is null in the new list.');
            
        // }
    }
    
    public static void haldleDelete(List<Quote__C> old) {
        
        id quoteId=old[0].QuoteId__c; 
        if(quoteId!=null){
        double amount=0.00;
        list<Quote__c>  quoteamountlist =[select id,TotalPrice__c,QuoteId__c from Quote__c where QuoteId__c =:quoteId];
        
        if(quoteamountlist!=null){
            system.debug('amount before delete tri'+amount);
            for(Quote__c qu:quoteamountlist){
                if(qu.TotalPrice__c!=null){
                    amount+=qu.TotalPrice__c;
                }
            }
            system.debug('lineno16 tri'+amount);
        }
        Quote__c  quoToUpdate=new  Quote__c();
        quoToUpdate.Id=quoteId;
        quoToUpdate.Subtotal__c=amount;
        system.debug('amount jjshjsh tri'+quoToUpdate);
        if(quoToUpdate!=null){
            update quoToUpdate;
        }
        }
        
    }
    
    
}