force-app/main/default/objects/Account/fields/Path_Status__c.field-meta.xml
<CustomField>
    <fullName>Path_Status__c</fullName>
    <defaultValue>&quot;Unqualified&quot;</defaultValue>
    <label>Path Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unqualified</fullName>
                <default>true</default>
                <label>Unqualified</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Dealer Onboarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>false</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>My Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunitiy Products</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Primary_contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account_Name__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/leadSucessClass.cls
public class leadSucessClass {

    @AuraEnabled(cacheable=true)
    public static String getAccountDetails(String accountId ) {
        Account acc = [SELECT Id, Name, Phone, Path_Status__c, Area__c, Owner.Name
                  FROM Account
                  WHERE Id = :accountId
                  LIMIT 1];
        
        String accountJson = JSON.serialize(acc);
        return accountJson;
    }

    @AuraEnabled(cacheable=true)
    public static String getContactDetails(string contactId) {
        system.debug('contactId'+contactId);
        Contact contacts = [SELECT Id,Name,Phone, Email,Account.Name 
                                  FROM Contact
                                  WHERE Id = :contactId 
                                  LIMIT 1];
        String contactJson = JSON.serialize(contacts);
        return contactJson;
    }

    @AuraEnabled(cacheable=true)
    public static String getOpportunityDetails(String oppId) {
        if(oppId!= null){
        Opportunity__c opportunities = [SELECT Id, Name,Close_Date__c, Amount__c, Owner.Name, Primary_contact__r.Name,Account_Name__r.Name
                                            FROM Opportunity__c 
                                            WHERE Id = :oppId 
                                        LIMIT 1];
            
        if(opportunities != null){
        String opportunityJson = JSON.serialize(opportunities);
            return opportunityJson;
        }
        else {
            return 'Null';
        }
       // if(opportunityJson != null){
        }
        return 'Null';
        
        
            
        }
    }